version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  module_system = "es-modules"
  dialect = "typescript"
  skip_doc_coverage = ["class-expression", "method-definition"]
  cyclomatic_complexity_threshold = "high"
